{
 "title": "HackUDC2026",
 "time": { "from": "2026-02-28T23:51:10.897Z", "to": "2026-03-01T01:08:03.397Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "KPIs Críticos",
   "type": "stat",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  (SELECT COUNT(*) FROM user) AS \"Total Usuarios\",\n  (SELECT COUNT(*) FROM question) AS \"Total Preguntas\",\n  (SELECT AVG(\n    CAST(strftime('%Y', 'now') AS INTEGER) - CAST(strftime('%Y', date_of_birth) AS INTEGER)\n  ) FROM user) AS \"Edad Media\";",
     "rawQueryText": "SELECT \n  (SELECT COUNT(*) FROM user) AS \"Total Usuarios\",\n  (SELECT COUNT(*) FROM question) AS \"Total Preguntas\",\n  (SELECT AVG(\n    CAST(strftime('%Y', 'now') AS INTEGER) - CAST(strftime('%Y', date_of_birth) AS INTEGER)\n  ) FROM user) AS \"Edad Media\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Health check",
   "type": "stat",
   "description": "Monitorización en tiempo real de la disponibilidad del backend (API). Este panel consulta el endpoint /health de forma recurrente para verificar la conectividad, la respuesta del servidor y el estado de la base de datos. ",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://host.docker.internal:8008/health",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Evolución Histórica de Usuarios",
   "type": "timeseries",
   "description": "Muestra el crecimiento total de la plataforma frente a los nuevos registros.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT \n  unixepoch(strftime('%Y-%m-%d %H:00:00', created_at)) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY created_at) AS \"Total Users\",\n  COUNT(*) AS \"New Users\"\nFROM \"user\"\n-- ESTA ES LA PARTE QUE CENTRA LA DATA:\nWHERE created_at >= datetime(-73456/1000, 'unixepoch')\n  AND created_at <= datetime(463732/1000, 'unixepoch')\nGROUP BY 1\nORDER BY 1;",
     "rawQueryText": "SELECT \n  unixepoch(strftime('%Y-%m-%d %H:00:00', created_at)) AS time,\n  SUM(COUNT(*)) OVER (ORDER BY created_at) AS \"Total Users\",\n  COUNT(*) AS \"New Users\"\nFROM \"user\"\n-- ESTA ES LA PARTE QUE CENTRA LA DATA:\nWHERE created_at >= datetime($__from/1000, 'unixepoch')\n  AND created_at <= datetime($__to/1000, 'unixepoch')\nGROUP BY 1\nORDER BY 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Latencia media vs. Tokens usados de media",
   "type": "stat",
   "description": "Correlación entre el tiempo de respuesta (latencia) y el volumen de tokens procesados. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%H:%M', q.date_time) AS \"Hora\",\n  q.time_out AS \"Segundos\",\n  q.used_tokens / 100.0 AS \"Tokens (x100)\" \nFROM question q\nORDER BY q.date_time DESC\nLIMIT 100;",
     "rawQueryText": "SELECT \n  strftime('%H:%M', q.date_time) AS \"Hora\",\n  q.time_out AS \"Segundos\",\n  q.used_tokens / 100.0 AS \"Tokens (x100)\" \nFROM question q\nORDER BY q.date_time DESC\nLIMIT 100;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Satisfacción del Usuario",
   "type": "gauge",
   "description": "Proporción de feedback sobre las preguntas realizadas.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  CASE \n    WHEN \"like\" = 1 THEN 'Like OK'\n    ELSE 'Like Mal' \n  END AS metric,\n  COUNT(id) AS value\nFROM question\nGROUP BY metric;",
     "rawQueryText": "SELECT \n  CASE \n    WHEN \"like\" = 1 THEN 'Like OK'\n    ELSE 'Like Mal' \n  END AS metric,\n  COUNT(id) AS value\nFROM question\nGROUP BY metric;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Usuarios con más preguntas  (Top Curiosos)",
   "type": "bargauge",
   "description": "Clasificación de los usuarios según la cantidad de preguntas publicadas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  u.username AS metric,\n  COUNT(q.id) AS value\nFROM user u\nJOIN question q ON u.id = q.user_id\nGROUP BY u.username\nORDER BY value DESC\nLIMIT 10",
     "rawQueryText": "SELECT \n  u.username AS metric,\n  COUNT(q.id) AS value\nFROM user u\nJOIN question q ON u.id = q.user_id\nGROUP BY u.username\nORDER BY value DESC\nLIMIT 10",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Últimas Preguntas",
   "type": "table",
   "description": "Registro detallado de las preguntas más recientes integradas con el perfil del usuario. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT \n  u.username AS \"Usuario\",\n  q.title AS \"Pregunta\",\n  (strftime('%Y', 'now') - strftime('%Y', u.date_of_birth)) AS \"Edad\",\n  strftime('%H:%M - %d/%m', q.date_time) AS \"Fecha\"\nFROM user u\nJOIN question q ON u.id = q.user_id\nORDER BY q.id DESC\nLIMIT 5;",
     "rawQueryText": "SELECT \n  u.username AS \"Usuario\",\n  q.title AS \"Pregunta\",\n  (strftime('%Y', 'now') - strftime('%Y', u.date_of_birth)) AS \"Edad\",\n  strftime('%H:%M - %d/%m', q.date_time) AS \"Fecha\"\nFROM user u\nJOIN question q ON u.id = q.user_id\nORDER BY q.id DESC\nLIMIT 5;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Distribución Demográfica por Edad",
   "type": "piechart",
   "description": "Reparto porcentual de nuestra base de usuarios según rangos de edad.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  CASE \n    WHEN (strftime('%Y', 'now') - strftime('%Y', date_of_birth)) < 18 THEN 'Menores'\n    WHEN (strftime('%Y', 'now') - strftime('%Y', date_of_birth)) BETWEEN 18 AND 30 THEN 'Jóvenes (18-30)'\n    WHEN (strftime('%Y', 'now') - strftime('%Y', date_of_birth)) BETWEEN 31 AND 50 THEN 'Adultos (31-50)'\n    ELSE 'Seniors (>50)' \n  END AS metric,\n  COUNT(id) AS value\nFROM user\nWHERE date_of_birth IS NOT NULL\nGROUP BY metric;",
     "rawQueryText": "SELECT \n  CASE \n    WHEN (strftime('%Y', 'now') - strftime('%Y', date_of_birth)) < 18 THEN 'Menores'\n    WHEN (strftime('%Y', 'now') - strftime('%Y', date_of_birth)) BETWEEN 18 AND 30 THEN 'Jóvenes (18-30)'\n    WHEN (strftime('%Y', 'now') - strftime('%Y', date_of_birth)) BETWEEN 31 AND 50 THEN 'Adultos (31-50)'\n    ELSE 'Seniors (>50)' \n  END AS metric,\n  COUNT(id) AS value\nFROM user\nWHERE date_of_birth IS NOT NULL\nGROUP BY metric;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}